### ISSUE TITLE
FBS: some NAICS dropping 

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#27] opened 2020-08-28 19:54 UTC
When expanding the NAICS list, more detailed sectors will get dropped if another entry in the mapping already maps to those sectors. [Line 119-120](https://github.com/USEPA/flowsa/blob/master/flowsa/mapping.py#L119)

With NEI data, some activities are more specific than others. E.g. an SCC might apply to all Agriculture (NAICS: 111) while another SCC will apply to specific crops (NAICS: 11114). When both are present, the first SCC won't get assigned to 11114 because it drops out from the mapping.

My preference would be to exclude this step but I dont know how that would impact other mappings. @catherinebirney

**Comment by catherinebirney** [comment] 2020-08-29 15:21
@bl-young Thanks for pointing this issue out.  It is a necessary step for some of the mappings I'm working with. I moved the "add_sectors_to_flowbyactivity" into the for loop that runs through each of the activities in the "names" list of an activity set. This way the NAICS are assigned to each SCC, one at a time, so the NAICS shouldn't be dropped.

**Comment by WesIngwersen** [comment] 2020-09-09 17:38
@bl-young let us know if this is still a problem or otherwise go ahead and close, thanks

**Comment by bl-young** [comment] 2020-09-15 20:55
I'm still getting unexpected results where the allocation to sectors is wrong. I will post a more detailed update.

**Comment by bl-young** [comment] 2020-09-16 00:59
Its still unclear to me why we are removing NAICS in [line 119](https://github.com/USEPA/flowsa/blob/master/flowsa/mapping.py#L119) that already exist in the mapping file

**Comment by catherinebirney** [comment] 2020-09-16 14:33
Ok - I see how the current method of implementation can cause problems. The objective is to prevent existing data from being overwritten. For instance, in the USDA_IWMS mapping, we have:
ORCHARDS =1113
BERRY TOTALS =111334
I want the water application rates (acre-feet/acre) for orchards disaggregated to naics6, but I don't want the acre-feet/acre for berry totals to be overwritten by the orchards value, so I was dropping the mapping 1113 -> 111334. 
The code needs to be revised so it doesn't blanket drop existing NAICS. Let me think about it...

**Comment by bl-young** [comment] 2020-09-16 14:41
But wouldn't you still want the value included in Orchards to apply to Berries just like all other subsets of 1113?

**Comment by catherinebirney** [comment] 2020-09-16 16:36
The issue is with how I set up the crosswalk for USDA IWMS. We can remove line 119 (and associated code).

**Closed** 2020-09-18 19:18 UTC
Labels: flowbysector

**Comment by bl-young** [comment] 2020-09-18 19:19
resolved [here](https://github.com/USEPA/flowsa/commit/cbbf8c11d6e989841080e82fc733f973877552af#diff-745db6dafd49c11e9c97307f1af6d0b1)
