### ISSUE TITLE
Check that NAICS coming in from NAICS like sources is present in our NAICS list for the given year

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#49] opened 2021-01-23 20:00 UTC
This is an issue discovered by @bl-young with a NAICS code coming in from RCRA via stewi that was not a valid 2012 NAICS code.
Related issue is here https://github.com/USEPA/useeior/issues/83

In any NAICS like sources we need to check that NAICS codes are in our NAICS code list.  If they are not present, we probably need to check if they are present in an older NAICS schema and see if we can apply a mapping to get it into the current NAICS schema (2012 at the moment)

**Comment by bl-young** [comment] 2021-01-23 20:08
This is more prevalent than those five flows in useeior suggest, as those flows only show up because they are _only_ found with those NAICS, but many other flows also use improper NAICS

**Comment by catherinebirney** [comment] 2021-01-26 14:07
@WesIngwersen @bl-young I'll address this issue while I'm working through updating the code to incorporate changes from the MasterCrosswalk

**Comment by bl-young** [comment] 2021-01-26 14:14
thanks! These data are coming from stewi and stewicombo, so depending on how you implement it, these data may already pass through the necessary function or we can add in `prepare_stewi_fbs` [here ](https://github.com/USEPA/flowsa/blob/master/flowsa/stewiFBS.py#L187)

**Comment by catherinebirney** [comment] 2021-01-26 14:18
Ah right, thanks for the reminder - I will keep that in mind

**Comment by catherinebirney** [comment] 2021-02-01 17:26
An update on this issue: I have a function that checks NAICS and outputs NAICS that are not NAICS 2012. The problem that I'm working through now is that NAICS 2007 -> NAICS 2012 is not necessarily a 1:1 mapping. For example NAICS 2007 '221119' maps to NAICS 2012 '221114', '221115', '221116', '221117'. and '221118'. Are there existing allocation ratios? Should I evenly allocate '221119' to the 5 NAICS 2012?
@bl-young @WesIngwersen

**Comment by bl-young** [comment] 2021-02-01 17:45
In my mind, I would expect that NAICS changes would be more likely than not to still be within the same BEA sector. So for consistency with other approaches, I think evenly allocating across the many NAICS mappings is the way to go. The particular example you describe is hopefully one that would be better resolved by the electricity disaggregation...but the point still holds. It seems it would take a fair bit more work to apply some kind of allocation for what hopefully is a fairly minor edge case.

**Comment by catherinebirney** [comment] 2021-02-01 18:44
Thanks Ben - I agree. I will equally allocate.

**Comment by WesIngwersen** [comment] 2021-02-01 22:01
OK this is fine for now since its unconsequential for our use cases. Let's just make sure its documented.

**Comment by bl-young** [comment] 2021-02-05 22:00
confirmed that this is working for me outside of that NAICS we identified from 2002 (541710)

**Comment by catherinebirney** [comment] 2021-02-08 13:08
I will pull in the 2002 naics to the crosswalk to convert '541710' to naics 2012

**Comment by catherinebirney** [comment] 2021-02-08 16:50
I added the 2002 crosswalk, so '541410' successfully converts to NAICS 2012

**Closed by catherinebirney** 2021-02-08 16:50 UTC
