### ISSUE TITLE
in geo.filtered_fips: TypeError: unhashable type: 'Series'

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#238] opened 2022-07-08 13:27 UTC
Obtaining the national FIPS code in `geo.filtered_fips` returns a TypeError

https://github.com/USEPA/flowsa/blob/a45e737d02a77d10cd358913cce5f4d13f7bef41/flowsa/geo.py#L89-L90

See for example this example code, fails on the third attempt.
```
import flowsa.geo as geo

geo.get_all_fips(2015).query('State != State') # option 1 see https://stackoverflow.com/a/46021212
geo.get_all_fips(2015).query('State.isnull()', engine='python') # option 2
geo.get_all_fips(2015).query('State.isnull()') # current method fails
```

I'm using pandas 1.3.3 and its possible this bug may be fixed in [pandas 1.4](https://github.com/pandas-dev/pandas/issues/22435). See [this comment](https://github.com/pandas-dev/pandas/issues/22435#issuecomment-916479899).

We either need to require pandas 1.4 or implment one of the options above

**Comment by matthewlchambers** [comment] 2022-07-08 22:02
If we want to maintain pandas 1.3.3 compatibility, I prefer option 2 as a fix. However, I think requiring pandas 1.4 is probably reasonable (in line with shifting the python requirement to 3.8), especially since my understanding is that 1.4 fixed quite a lot of bugs.

**Comment by matthewlchambers** [comment] 2022-07-11 12:58
Having done a little more research on this issue (to understand what other issues might be caused by this bug), I feel more strongly than before that it would be better to require pandas 1.4. For pandas < 1.4, this bug causes (or may cause) `.query()` to fail if the query string uses pandas `Series` methods. Option 1 is a fix that is very specific to the situation of checking for nulls, and option 2 (`engine='python'`) has performance implications which may be annoying with larger datasets.

On the whole, particularly given that this issue arises because of a bug which got fixed in pandas 1.4, it would be better to require 1.4 than to make potentially awkward fixes to accommodate the bug.

**Comment by bl-young** [comment] 2022-07-11 13:04
Noting that pandas 1.4 requires python >= 3.8, so relates to #237

**Comment by bl-young** [comment] 2022-07-11 19:12
Ok in that case https://github.com/USEPA/flowsa/commit/c6d261e982e4759e4a622d3080dcfa512345ea25 can be reverted and we can make a plan to update requirements (with hopefully few other issues)

**Closed** 2022-07-11 19:24 UTC
Labels: feature branch
